# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.7
    addToPath: true
  displayName: Install Python

- script: |
    python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install dependencies'

- script: |    
    python setup.py bdist_wheel 
  displayName: 'Artifact creation'

- script: python -m pip install --upgrade twine
  displayName: 'Install Twine'
- task: TwineAuthenticate@1
  inputs:
    pythonUploadServiceConnection: 'pypianymate'

- script: |
   python -m twine upload -r 'anymate' --repository-url 'https://upload.pypi.org/legacy' --config-file $(PYPIRC_PATH) dist/*.whl
  displayName: 'Publish to PyPi through Twine'